name: EAS Publish

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./SudokuApp

      - name: Install EAS CLI
        run: npm install -g eas-cli
        working-directory: ./SudokuApp

      - name: Log in to Expo
        run: eas whoami || echo "// no login needed with token"
        working-directory: ./SudokuApp

      - name: Publish to EAS Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr / -)
          eas update --branch $BRANCH_NAME --message "Auto-publish from $BRANCH_NAME"
        working-directory: ./SudokuApp

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./SudokuApp

      - name: Build web version
        run: npx expo export --platform web --output-dir web-build
        working-directory: ./SudokuApp

      - name: Upload web build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: ./SudokuApp/web-build
          retention-days: 5

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./SudokuApp/web-build
          branch: gh-pages
          clean: true