# This workflow builds a preview of the Expo web app for each pull request
name: Expo Web – PR Preview

on:
  pull_request:
    branches: [main]

# -------------------------------------------------------------------------
permissions:
  contents: read        # checkout
  pages: write          # request a Pages build
  id-token: write       # auth for deploy-pages

env:
  APP_DIR: SudokuApp
  NODE_VERSION: 18

jobs:
# ────────────────────────────── BUILD ────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true # This is important for the GitHub Pages deploy

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./SudokuApp

      - name: Build web version
        run: |
          # Use the correct export command for web platform
          npx expo export --platform web
        working-directory: ./SudokuApp

      - name: Prepare web build for deployment
        run: |
          # Move dist contents to web-build directory for consistency
          mkdir -p web-build
          cp -r dist/* web-build/
        working-directory: ./SudokuApp

      - name: Upload web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: ./SudokuApp/web-build
          retention-days: 5

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./SudokuApp/web-build
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}