
# ──────────────────────────────────────────────────────────────────────────
# Builds the Expo web bundle from the SudokuApp sub‑directory
# and publishes an isolated PR‑preview site via GitHub Pages.
# Every open PR gets its own URL, e.g.:
#   https://pr‑42‑mjohnson139.githubpreview.dev/expo-sudoku/
name: Expo Web – PR Preview

on:
  pull_request:
    branches: [main]

# -------------------------------------------------------------------------
permissions:
  contents: read        # checkout
  pages: write          # request a Pages build
  id-token: write       # auth for deploy-pages

env:
  APP_DIR: SudokuApp
  NODE_VERSION: 18

jobs:
# ────────────────────────────── BUILD ────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    # Allow both main branch deployments and feature branch builds (but only deploy from main)
    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Export static web build
        run: npx expo export --platform web --output-dir web-build --non-interactive

      # Debug steps for build verification
      - name: Enhanced debugging
        run: |
          echo "Current directory: $(pwd)"
          echo "Content of current directory:"
          ls -la
          echo "Content of web-build directory (if exists):"
          ls -la web-build || echo "web-build not found in current directory"
          echo "App directory content:"
          ls -la ${{ env.APP_DIR }}

      # If using the new GitHub Pages Deployment Action (recommended 2024+)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.APP_DIR }}/web-build

      # Only deploy from main branch
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3    # official GA release
        if: github.ref == 'refs/heads/main'